# docker compose 版本
version: "3.9"

services:
  # zookeeper 节点1
  zk1:
    # 镜像名称
    image: zookeeper
    # 容器名称
    container_name: zk1.docker
    # docker重启后自动重启容器
    restart: always
    # 当前容器主机名
    hostname: zk1.docker
    # 端口 宿主机:容器
    ports:
      - "2181:2181"
    # 环境变量
    environment:
      # myid，一个集群内唯一标识一个节点
      ZOO_MY_ID: 1
      # 集群内节点列表
      ZOO_SERVERS: server.1=zk1.docker:2888:3888;2181 server.2=zk2.docker:2888:3888;2181 server.3=zk3.docker:2888:3888;2181
  # 节点2
  zk2:
    image: zookeeper
    container_name: zk2.docker
    restart: always
    hostname: zk2.docker
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1.docker:2888:3888;2181 server.2=zk2.docker:2888:3888;2181 server.3=zk3.docker:2888:3888;2181
  # 节点3
  zk3:
    image: zookeeper
    container_name: zk3.docker
    restart: always
    hostname: zk3.docker
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1.docker:2888:3888;2181 server.2=zk2.docker:2888:3888;2181 server.3=zk3.docker:2888:3888;2181