# 配送系统的端口号要与订单系统不一样
server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    port: 5672
    publisher-confirms: true # 配置生产者确认机制
