server:
  port: 8090
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
mybatis:
  type-aliases-package: com.qiaoyn.xadmin.entity   # 实体类位置
  mapper-locations: classpath:/mapper/*.xml   #  mapper位置
  configuration:
    map-underscore-to-camel-case: true  # 驼峰转换
logging:
  level:
    com:
      qiaoyn:
        xadmin:
          mapper: debug