spring:
  jackson:
    time-zone: GMT+8
  shardingsphere:
    datasource:
      names: master,slave1,slave2
      master:
        url: jdbc:mysql://43.143.142.233:3339/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name:  com.mysql.jdbc.Driver
      slave1:
        url: jdbc:mysql://43.143.142.233:3340/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name:  com.mysql.jdbc.Driver
      slave2:
        url: jdbc:mysql://43.143.142.233:3340/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name:  com.mysql.jdbc.Driver
    masterslave:
      load-balance-algorithm-type: round_robin
      name: ms
      # 指定主数据源
      master-data-source-name: master
      slave-data-source-names: slave1,slave2
    props:
      sql:
        show: true
